#!/bin/sh

# Generate CHANGES.darcs
[ -d "$DARCS_REPO" ] && darcs changes --repodir "$DARCS_REPO" > CHANGES.darcs

# Build the user manual for release
cd manual
make manual.pdf
# Remove intermediate files
make clean-aux
cd ..

# Add oasis stuff
oasis setup

# Set release mode in the Makefile
sed -i 's/^SETUP := setup-dev.exe.*/SETUP := setup.exe/' Makefile

# Cleanup
rm -f predist boring dist.sh
